### ISSUE TITLE
Wrong line endings after installation

### ISSUE THREAD

**Issue by jongbelegen** [sainthkh/reasonql#14]
I think this issue is related to:
https://github.com/yarnpkg/yarn/issues/5480

After installing with yarn on mac os i get the following error:
`/usr/bin/env: «node\r»: No such file or directory`

After using dos2unix on these files it works again.

Could we fix this in the package?

**Comment by xla** [comment]
Encountered the same issue over the weekend.

@jongbelegen Doesn't the yarn issue indicate that it happens during installation? Can it be fixed in the source repo?

**Comment by jongbelegen** [comment]
@xla For me adding [.gitattributes](https://github.com/jongbelegen/reasonql/blob/fix/line-endings/.gitattributes) did the trick.

**Comment by xla** [comment]
Opened #15 to address it.
