### ISSUE TITLE
Broken link on Redex

### ISSUE THREAD

**Issue by vog** [sainthkh/reasonql#6]
The link to "Why I started this project" on Redex is broken:

* https://redex.github.io/package/@reasonql/core/

It points to the following non-existing page:

* https://redex.github.io/package/@reasonql/core/WHY.md

**Comment by sainthkh** [comment]
Hmm... I should change the link to absolute path.

**Comment by sainthkh** [comment]
I fixed links and published the 0.1.3 version. Now, we need to wait for Redex to update the information. 

Thank you!

**Comment by sainthkh** [comment]
If we want to read the fixed version, [please check here](https://github.com/sainthkh/reasonql/blob/master/packages/core/README.md).

**Comment by vog** [comment]
The link works on GitHub, but does not work on Regex:

* https://redex.github.io/package/@reasonql/core/

The link "Why I started this project" points to:

* https://redex.github.io/package/WHY.md

which throws a 404 error.
